### ISSUE TITLE
Lost Connection to Matchmaking service

### ISSUE THREAD

**Issue by megastruktur** [SlejmUr/PayCheck3#11]
Hi guys,
I receive "Lost Connection to Matchmaking service" while trying to start a new game. Am I missing something?

**Comment by SlejmUr** [comment]
Work as expected, matchmaking code isn't finished

**Comment by megastruktur** [comment]
@SlejmUr oh sorry. Is there a way it could be played right now?

**Comment by SlejmUr** [comment]
Offline mode via mods

**Comment by megastruktur** [comment]
@SlejmUr if this is legal - do you know any?  :)
Sorry for bringing that one here though internet search gives me nothing  :(

**Comment by SlejmUr** [comment]
You can google something like "is emulating servers legal" you get your answer.

I myself think yes because I not using any of SBZ Code for this project.
But I am not a laywer

**Comment by megastruktur** [comment]
@SlejmUr nono, I mean, the mod. Can't find any mod to use it for playing...

**Comment by SlejmUr** [comment]
I dont want to give you direction where to get those, If you look enough you can find mods, or play on sbz servers
(delete the stuff you put in the hosts file), another option is waiting :) [Or help me figure out this stuff but yeah]
