### ISSUE TITLE
Can't compile the server exe

### ISSUE THREAD

**Issue by wezu123** [SlejmUr/PayCheck3#13]
Hey, it's not a problem with your project, but rather with me. I can't find the .exe, nor can I compile the project in VS. I cloned the repo, and then I tried running/publishing it, but I got errors saying it can't find packages NetCoreServer, JWT, and L in Microsoft VS Offline Packages, and Newtonsoft.Json is outdated. I'm probably doing something very wrong. I'd appreciate the help if you could find a minute, I think the project looks cool and wanted to check it out, thanks!

**Comment by SlejmUr** [comment]
Did you installed your VS with Nuget package manager?
It is a handy tool, and I use that for all those packages

**Comment by wezu123** [comment]
I downloaded the VS from Microsofts website. Now it says it can't recognize element "JWT" (and other packages) for element "net7.0". I'm lost lol

**Comment by SlejmUr** [comment]
If you havent please install .net SDK
https://dotnet.microsoft.com/en-us/download/dotnet/7.0

Also it will be good if you can say which Visual Studio version did you downlaoded

**Comment by wezu123** [comment]
I installed it, and the net7.0 errors still appear, I'm using Visual Studio Community 2022

**Comment by RavinMaddHatter** [comment]
Wezu if you are building to help that is cool, but just making sure, you didnt just miss that there are compiled binaries here 

https://github.com/SlejmUr/PayCheck3/actions/runs/6278839824

In the artifiacts

**Comment by wezu123** [comment]
For some reason when I was checking it yesterday, there was only Paycheck3-Artifact, so I thought it wasn't it, now I can see the Windows archive.
The server runs, although I'm getting the Nebula Error upon logging.

**Comment by SlejmUr** [comment]
Are you sure you made a cert?
Are you sure installed as Local Machine and Trusted Root Cert Auth?
Are you sure you edited your hosts file?

**Comment by wezu123** [comment]
Ok, I managed to get it to work, cloned the repo again with git, imported the certs again, and got the newest release, although lvl 1, probably different save than live, guessing same save for Paycheck 3 and live servers is not possible, but that's fine I guess. So now we're waiting for the matchmaking to get fixed. I'm guessing once it works I can just set up Hamachi, change their hosts file and we can play together?

Thanks for the work you're putting in.

**Comment by SlejmUr** [comment]
Haha, matchmaking with other users and actually playing is need more things than just that :)
I didn't know what to do first, do mm or qol features

**Comment by wezu123** [comment]
Yeah, I figure it's not easy lol. I'd say looking if MM is gonna work at all and then qol, but that's your project so do as you wish

**Comment by SlejmUr** [comment]
Yeah, since you have build the exe I close this
