### ISSUE TITLE
Match Making Doesn't work

### ISSUE THREAD

**Issue by RavinMaddHatter** [SlejmUr/PayCheck3#15]
I see this in the readme now. I am not trying to push you to do anything, but wanted to file an issue incase anyone like me is looking at the issues to see if there are any deal breakers.

Assuming you have configured correctly you will reach the main menu
After selecting a heist you will recieve an error that looks like this 
![image](https://github.com/SlejmUr/PayCheck3/assets/4407668/b8cccdf7-7e50-412a-8061-aa9de38b26eb)

At this point the paycheck 3 service will have a dump that looks like this 

`[INFO] Nothing was sent to WSS
GS Sent!
[DEBUG] /basic/v1/public/misc/time
[INFO] Url Called function: Time
[DEBUG] 8ea6535cfd1da18944e424e63952c116(DefaultUser) Is still in the server!
[DEBUG] /iam/v3/public/namespaces/pd3/platforms/steam/users?rawPUID=true
something isnt good
GS Sent!
[DEBUG] /basic/v1/public/misc/time
[INFO] Url Called function: Time`

Reducing the log writes in the long run may speed up the server quite a bit.

[2023-09-22.log](https://github.com/SlejmUr/PayCheck3/files/12703768/2023-09-22.log)

**Comment by RavinMaddHatter** [comment]
After you get things working, i will help put together some readme stuff and document. I am not a C# person so not very helpful on that front but i can put stuff in a Wiki or in the readme

**Comment by RavinMaddHatter** [comment]
I will say getting to the login screen is more reliable than the offical servers... so that is a big win.

**Comment by Power2All** [comment]
Wished it was coded in Rust, so we could have a reliable, ultra fast, multi-threaded, lock-free system. Seeing how this game uses pure WebSockets, HTTPS and UDP packets, shouldn't be hard seeing this project.
If you need any help figuring out what's up, let me know.

**Comment by Power2All** [comment]
Found possible issue.
It checks for platform ID's at Steam:
Request URL: /iam/v3/public/namespaces/pd3/platforms/steam/users?rawPUID=true

It returns a array of platformUserIds.
None of them is my Steam ID, so it's perhaps crapping out on this ?

**Comment by SlejmUr** [comment]
https://github.com/SlejmUr/PayCheck3#currently-matchmaking-is-not-working

As I said before the matchmaking is not working.

> help put together some readme stuff and document

I would love to get some of the docs or documents, I bad at writing them (I usually put Technical info in them, so no so user friendly)


> Wished it was coded in Rust

I wish I wouldnt even needed to code in this project :) But because rust is low level (or lower level than C#) and I really bad at managing memory, stuff, I dont think I would make a better Rust project with this.
But If you do, and you can help me in some way. Feel free to do so :)

> Request URL: /iam/v3/public/namespaces/pd3/platforms/steam/users?rawPUID=true

That ask all your friends (from steam) are exist in the server.
If they exist it return their UserId (From Server) with their PlatfromID (SteamId), Not implemented yet, but will do in the future.

**Comment by Power2All** [comment]
> I wish I wouldnt even needed to code in this project :) But because rust is low level (or lower level than C#) and I really bad at managing memory, stuff, I dont think I would make a better Rust project with this.
But If you do, and you can help me in some way. Feel free to do so :)

Rust ain't that hard.
Currently running a Torrent Tracker purely made in Rust, handling 12k connections per second.
Rust is basically just C++ on steroids though, and you can code it pretty well using threading in Tokio Threads, without Mutexes or RWlock that could deadlock your app.
I never did any game emulation though, however, I do know how it kind of works.
Going to make a simple proxy and man-in-the-middle app later to see what PayDay 3 is actually trying to transmit.

**Comment by SlejmUr** [comment]
well, have fun, I would be interested in udp con and things

The c++ in steroids seems little scary since I only edited a small things on C/c++

**Comment by Power2All** [comment]
> well, have fun, I would be interested in udp con and things
> 
> The c++ in steroids seems little scary since I only edited a small things on C/c++

Well, it's basically heavy type sensitive, and it will scream on anything that could make memory corruption, compared to C# or C++ that crashes after you run it. That makes Rust very reliable, and it will make your life much happier, knowing you can avoid possible memory conflicts, where the compiler will already scream you cannot do that ;)

**Comment by RavinMaddHatter** [comment]
Rust is a language that rust people love but it is so far disconnected from other languages that you really struggle to get open source development happening. Just saying... Rust is the wrong language if you want others to help...

**Comment by Power2All** [comment]
> Rust is a language that rust people love but it is so far disconnected from other languages that you really struggle to get open source development happening. Just saying... Rust is the wrong language if you want others to help...

I disagree with you on that though.
It's actually very close to C++ and GO.
People just don't seem to understand how the Structs work as Result<> and Option<> and such.

**Comment by RavinMaddHatter** [comment]
Just saying throw a shoe and your hit a python or c# dev... look long and
hard to find a rust dev.

**Comment by SlejmUr** [comment]
Well Since the topic changed I close this.
Feel free to make a Rust clone from this or something if you are dedicaded enough, just write me an email to check it or smth.
Maybe you can improve something and can be ported here in C#

**Comment by RavinMaddHatter** [comment]
Do you want logs from newer builds?

**Comment by SlejmUr** [comment]
Its all the same, no. I have everything ready to code the MathcMaking function

If you have Nebula Connection error, delete every folder , except Files (+ relaucnh the game)
