### ISSUE TITLE
I'm getting these errors.

### ISSUE THREAD

**Issue by GhaithA-M** [SlejmUr/PayCheck3#16]
CS0006	Metadata file '\PayCheck3-master\PayCheckServerLib\obj\Release\net7.0\ref\PayCheckServerLib.dll' could not be found

MSB3073	The command "git describe --long --always --exclude=* --abbrev=8" exited with code 128

MSB3073	The command "git.exe branch --show-current > "\PayCheck3-master\PayCheckServerLib\\Properties\BuildDate.txt"

**Comment by SlejmUr** [comment]
You need to install GIT (preferably a CLI version too)

**Comment by GhaithA-M** [comment]
![image](https://github.com/SlejmUr/PayCheck3/assets/122114790/4ed71c71-1d3e-4603-a0f8-e7dc5fa33e5f)
![Screenshot_2](https://github.com/SlejmUr/PayCheck3/assets/122114790/5a334ac0-e449-4374-8b27-4fe1181d2d2e)

Both these versions seem to give the same error. Perhaps the missing "PayCheckServerLib.dll" is the cause?

**Comment by SlejmUr** [comment]
if you type "git --version" in your console does it print out the version?
If not you may have PATH issues

**Comment by helloworlduser99** [comment]
I am getting the same error when download the project. Clone this project to a directory worked for me.

**Comment by SlejmUr** [comment]
Have you managed to fix it?
