### ISSUE TITLE
How i know if the server is starting?

### ISSUE THREAD

**Issue by DocLeif** [SlejmUr/PayCheck3#18]

**Comment by DocLeif** [comment]
Or running?

**Comment by RavinMaddHatter** [comment]
Did you read that you can't actually play rounds yet. Once it is functional
I will write some docs for stuff like this

**Comment by SlejmUr** [comment]
If you write it yes, its gonna work :)

**Comment by KyRuS-SH** [comment]
If your server is running correctly it should look something like this:

![grafik](https://github.com/SlejmUr/PayCheck3/assets/57010770/810f0d23-ead0-4595-914b-cf400e8ab668)

As @RavinMaddHatter pointed out Match Making is currently not working.

**Comment by SlejmUr** [comment]
Debug stuff AFTER MM finished gonna can be enabled with -debug
