### ISSUE TITLE
where's the .EXE

### ISSUE THREAD

**Issue by Yan1982** [SlejmUr/PayCheck3#19]
i've read the readme.md, followed the instrutions but i can't find the .exe, in the PayCheck3 folder there's only a .csproj file and a .cs file

**Comment by SlejmUr** [comment]
[Github Actionns](https://github.com/SlejmUr/PayCheck3/actions)

**Comment by KyRuS-SH** [comment]
Head on over to the Actions Tab (https://github.com/SlejmUr/PayCheck3/actions).

There you select one of the recent builds and scroll down.
It's the artifacts section:
![grafik](https://github.com/SlejmUr/PayCheck3/assets/57010770/4d537b03-afd7-47ab-be1a-99e765432500)

Please take note of the disclaimer that matchmaking is currently not working.
