### ISSUE TITLE
i cannot connect to the server.

### ISSUE THREAD

**Issue by DocLeif** [SlejmUr/PayCheck3#21]

**Comment by SlejmUr** [comment]
picture, log? anything?

**Comment by DocLeif** [comment]
![Screenshot 2023-09-22 224729](https://github.com/SlejmUr/PayCheck3/assets/145805517/17e45e46-dd17-4e2a-a83f-316e994239de)

**Comment by DocLeif** [comment]
whats wrong?

**Comment by SlejmUr** [comment]
why are you trying to start that server inside the SYSTEM32? (or as system32)
if you remove the " it maybe can run

**Comment by DocLeif** [comment]
![Screenshot 2023-09-22 225314](https://github.com/SlejmUr/PayCheck3/assets/145805517/e91f79f8-8992-4785-a221-0bc010e589a9)

**Comment by DocLeif** [comment]
no its not working i think

**Comment by SlejmUr** [comment]
You forget to make a cert file

**Comment by DocLeif** [comment]
![Screenshot 2023-09-22 225622](https://github.com/SlejmUr/PayCheck3/assets/145805517/59a8ea0c-ae45-4e43-ae3a-bb581af50f21)

**Comment by DocLeif** [comment]
both of them are in the folder

**Comment by DocLeif** [comment]
what can i do?

**Comment by SlejmUr** [comment]
Are the pfx password is cert?
Are you sure?
Then try again

**Comment by DocLeif** [comment]
cert, yes

**Comment by DocLeif** [comment]
i am sure. and i was creating it again to check it. but still the same problem

**Comment by DocLeif** [comment]
Is there still a solution?

**Comment by SlejmUr** [comment]
It work on my and many others machines, even works on Linux too.
No idea what not works for you

**Comment by SlejmUr** [comment]
But since servers are up rn, delete the 2 lines in your host file that you added and can play on official servers

**Comment by DocLeif** [comment]
OK, I'll keep trying. Thanks anyway
