### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by Reziem** [SlejmUr/PayCheck3#27]
I find myself confused on the process of having my friends join me. Could you clarify whether they also require the server emulator installed on their PCs, or is it solely my responsibility?

If it's only me running the emulator, do my friends still need to make adjustments to their hosts file with my public IP address? We've attempted this, but unfortunately, they're encountering connectivity issues. Could there be something that I've overlooked?

I also have port forwarded the computer that is hosting the server emulator.

**Comment by HW12Dev** [comment]
multiplayer is not currently supported or implemented in PayCheck3, but if you wish to make the server public facing on the internet, you'll need to set the ip it uses to 0.0.0.0 and ensure your friends have your self signed certificate installed

**Comment by SlejmUr** [comment]
Plus yes they need to change their hosts file to your IP instead of 127.0.0.1

**Comment by Reziem** [comment]
> multiplayer is not currently supported or implemented in PayCheck3, but if you wish to make the server public facing on the internet, you'll need to set the ip it uses to 0.0.0.0 and ensure your friends have your self signed certificate installed

Sorry for my confusion, If multiplayer is not supported then It wouldn't make much sense to have my friends walk through the process or does it still work to play together? In a peer 2 peer kind of way?

**Comment by SlejmUr** [comment]
In the game currently p2p function is deleted.
And yes currently waiting me to implement better things at lobby, gamesession (matchmaking) and will be a dedicated server.
Currently only works that you can play the game offline mode (if you have mods installed)
