### ISSUE TITLE
Error:  "The given key 'cookie' was not present in the dictionary."

### ISSUE THREAD

**Issue by OwenMcintosh** [SlejmUr/PayCheck3#28]
```
[ERROR] No cookie in header!
[ERROR] System.Collections.Generic.KeyNotFoundException: The given key 'cookie' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PayCheckServerLib.TokenHelper.ReadFromHeader(Dictionary`2 kv) in D:\a\PayCheck3\PayCheck3\PayCheckServerLib\Helpers\TokenHelper.cs:line 146
```
   
Followed the steps provided, yet still failing at nebula game config data fetch. 

Installed certificates to the correct locations, as well as pasting them into the server folder, as well as editing the "hosts" file.

![image](https://github.com/SlejmUr/PayCheck3/assets/78048040/96c5e1ca-92ad-4348-955c-732933786021)

**Comment by SlejmUr** [comment]
The "No cookie in header" comes from the time things. For me works ws expected.
Try deleting your save file and run again,dont know why is that happening for me too

**Comment by SlejmUr** [comment]
Fixed in latest gs-mm Branch
