### ISSUE TITLE
Doesnt quite work with official game :(

### ISSUE THREAD

**Issue by Jacob-Tate** [SlejmUr/PayCheck3#5]
Not sure where you are on development of this but currently attempting this results in the following:

![image](https://github.com/SlejmUr/PayCheck3/assets/4615660/29f3497e-ddee-47b3-aff3-8d0dfcee4e3b)

see later comment for log file

**Comment by SlejmUr** [comment]
Next time please upload somewhere the log file!

About Not connected:
Are you sure you installed your certificate as Local Machine and Trusted Root Cert. Authority?
Please check that, it causes this error usually

**Comment by jasonmerc** [comment]
I installed both the PFX and CRT, this same error still happens to me.

**Comment by Jacob-Tate** [comment]
It appears you were correct I installed them into the wrong store.

@jasonmerc make sure when you run the installed select the correct store 
![image](https://github.com/SlejmUr/PayCheck3/assets/4615660/f9f66919-616f-464a-adbd-091271d77c01)

That being said while I can login now I am still having an issue when attempting to queue into a game.

![image](https://github.com/SlejmUr/PayCheck3/assets/4615660/bc5fcbc5-55d1-474f-96ca-7cb3243ac91b)

**Comment by jasonmerc** [comment]
Thank you, I was actually just about to post the same thing.  I got it installed about a minute ago.

**Comment by jasonmerc** [comment]
[readme.txt](https://github.com/SlejmUr/PayCheck3/files/12694129/readme.txt)

Here is an updated Readme in the Cert folder, explaining how to do what was outlined above.  If the main dev wants to put this into their project they are free to do so.

**Comment by SlejmUr** [comment]
Queue not work as the main readme says, because that function still working on.

And thanks for the updated cert readme
