### ISSUE TITLE
Question - Instructions for Compiling

### ISSUE THREAD

**Issue by jasonmerc** [SlejmUr/PayCheck3#6]
There are no binary releases, so we have to compile the C# code ourselves to get this working.

I wanted to ask the dev, is there a particular way we should be doing this?  Like, a particular Visual Studio version?  A particular .NET version?

**Comment by SlejmUr** [comment]
In here at GitHub every push or pull request getting builded by Actions, you can pick any from there. (I always prefer latest)

For VS version I using vs22, for .NET is 7

**Comment by jasonmerc** [comment]
Thank you, I didn't know GitHub did that.

Could you put that on the main Readme as well?  Other people who aren't inclined with this would probably ask the same thing in the future.

**Comment by SlejmUr** [comment]
Tomorrow with some changes will be added along with this!

Please reopen if I forgot.

(Wait till 2day, then)
