### ISSUE TITLE
Configure HTTP Server Port

### ISSUE THREAD

**Issue by ImperatorStorm** [SlejmUr/PayCheck3#7]
Can you add the ability to change the http server port via `config.json`? I already have a webserver hosted on `127.0.0.1:443`, and I don't see any way to change the port outside of changing the source code and recompiling.

**Comment by SlejmUr** [comment]
If you can edit the game to connect to that port, let me know, if you make it work I will add into it.

But because the game automatically connects to https://ip:443/ & wss://ip:443/ didn't through about you can change their connection port to something else

**Comment by SlejmUr** [comment]
the IP changed for can host other than 127.0.0.1
Still need something for you to parse the port from 443 to something else (like 8888)

**Comment by janisslsm** [comment]
PAYDAY3\Config\DefaultEngine.ini contains URLs for the servers (https://nebula.starbreeze.com and https://development.starbreeze.accelbyte.io), those could most likely be changed to 127.0.0.1:8888 or something of that sort. I haven't tested it yet but theoretically should work.

**Comment by SlejmUr** [comment]
we tested back on Beta, and the http worked but still asked with WSS sadly.
maybe somehow can bypass cert verify

**Comment by janisslsm** [comment]
the wss:// seems to be hard-coded in the executable so most likely would need to patch the executable itself aswell

**Comment by SlejmUr** [comment]
well, easier to found where the ssl verification happening and get rid of that, or patching that too

**Comment by ImperatorStorm** [comment]
Software like https://apache.org/ and https://caddyserver.com/ can reverse-proxy websites, e.g. the content from `127.0.0.1:2353` is displayed on `arbitrary.url:arbitrary_port`

**Comment by SlejmUr** [comment]
Added into latest gs-mm Branch
