### ISSUE TITLE
no exe? 

### ISSUE THREAD

**Issue by db123infane** [SlejmUr/PayCheck3#9]
"2. Copy crt & pfx files and paste next to PayCheck3ServerApp.exe" i only see the folder with a cs file and cs project file.

**Comment by megastruktur** [comment]
You need to download the Built server from here first: https://github.com/SlejmUr/PayCheck3/actions

Select the top entry, scroll bottom and download PayCheck3-artifact

**Comment by db123infane** [comment]
thanks
